### ISSUE TITLE
go build false: https://github.com/v2pro/plz/blob/master/gls/goid.go#L27:  missing function body

### ISSUE THREAD

**Issue by zbwang163** [v2pro/plz#12]

**Comment by leisurelicht** [comment]
Is this error solved？I had the same problem.

**Comment by zbwang163** [comment]
not yet.



At 2022-03-09 14:48:55, "暮晨" ***@***.***> wrote:

Is this error solved？I had the same problem.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by picone** [comment]
A function [here](https://github.com/v2pro/plz/blob/422184e41b6ec092816758d5ab7566b2337eb0fb/gls/goid.go#L27) has not been implemented in m1, so it fails. Need to implement `goid_arm64.s`.
